[package]
name = "aoc20"
version = "0.1.0"
edition = "2018"

[dependencies]
regex = "1"
anyhow = "1"
derive_builder = "0.9"
lazy_static = "1.4"
itertools = "0.9"
petgraph = "0.5"
nom = "6"
bimap = "0.5"
num = "0.3"
bitvec = "0.19.4"
thiserror = "1.0.22"
