[package]
name = "aoc20"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1"
bimap = "0.5"
bitvec = "0.19"
derive_builder = "0.9"
itertools = "0.9"
lazy_static = "1.4"
ndarray = "0.14"
nom = "6"
num = "0.3"
petgraph = "0.5"
regex = "1"
thiserror = "1.0"
