[package]
name = "aoc20"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1"
bimap = "0"
bitvec = "0.19"
derive_builder = "0"
itertools = "0"
lazy_static = "1"
ndarray = "0"
nom = "6"
num = "0"
petgraph = "0"
regex = "1.7"
thiserror = "1"
